### ISSUE TITLE
Pins don't get placed on Windwows

### ISSUE THREAD

**Issue by TrueDoctor** [gmplot/gmplot#97] opened 2019-02-19 22:28 UTC
The Path describing the icon location in the generated html document contains a mix of \ and / wich confuses the Webbrowser.

**Comment by TrueDoctor** [comment] 2019-02-20 11:10
this could be fixed in a rather dirt way, by manually replacing the backslashes in the String with forward facing slashes like so:
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png').replace('\\', '/'))
but there might be an more elegant way to do this

**Comment by frslm** [comment] 2020-04-28 04:27
Duplicate of #18.

**Closed** 2020-05-03 02:26 UTC
Labels: bug, duplicate
