### ISSUE TITLE
Marker=True in gmap.scatter don't work

### ISSUE THREAD

**Issue by ACinesi** [gmplot/gmplot#57] opened 2017-12-10 10:33 UTC
I think that the problem is how is generated the path. I searched in the generated html and I found that the path was:
**C:\Python27\lib\site-packages\gmplot\markers/FF0000.png**
I tried to change it manually in:
**file:///C:/Python27/Lib/site-packages/gmplot/markers/FF0000.png**
And it seems to work. Some comments about that??

**Comment by mvabdi** [comment] 2017-12-17 17:20
I figured it out, I think the issue is with the windows file system using forward slashes

Here's what I did to fix it without doing it manually every time

1. Find your gmplot folder, which for you is 'C:\Python27\lib\site-packages\gmplot\'
2. Open up gmplot.py
3. Find 'self.coloricon = '
4. Replace everything after the = sign with file:///' + os.path.dirname(__file__).replace('\\', '/') + '/markers/%s.png'
5. When choosing a marker for your scatter method, choose one of the ones in the marker folder, other wise it doesnt work

and that's it

**Comment by frslm** [comment] 2020-04-28 04:27
Duplicate of #18.

**Closed** 2020-05-03 02:26 UTC
Labels: bug, duplicate
