### ISSUE TITLE
marker does not work in the example code

### ISSUE THREAD

**Issue by wguo123** [gmplot/gmplot#63] opened 2018-03-08 19:05 UTC
gmap.marker(hidden_gem_lat, hidden_gem_lon, 'cornflowerblue')

The marker did not show up in the rendered map, is this a known issue or did I miss anything?

**Comment by vgm64** [comment] 2018-03-08 19:10
It works for me. Can you share an image of your map? Anything useful in the javascript console? What platform are you using?

**Comment by wguo123** [comment] 2018-03-08 19:16
Thanks for the quick response! Appreciate it!

I am using the sample code you provided in the read me file. I am using a windows machine. 

Here is the html map

https://drive.google.com/file/d/1ycw76gec-LzltLgLpFL4o9mXoRY1iuKs/view?usp=sharing

Here is the code:

https://drive.google.com/file/d/1U0WTcMOTCRm2cP-TqGG7LN56M7YtFuJB/view?usp=sharing

**Comment by wguo123** [comment] 2018-03-08 19:47
In fact, I just tried it on linux machine, it worked very well! Anything I can check on the Windows machine to make it function well?

**Comment by vgm64** [comment] 2018-03-08 21:00
There are some other issues raised on the repo for windows support. Check those out. I haven't merged them because they usually do some hardcoded replacements instead of using the os repo.

**Comment by Tsingis** [comment] 2018-07-26 08:33
I can't get any markers to show, not even with example code. I'm using windows machine.

**Comment by vgm64** [comment] 2018-07-27 04:01
More motivation for me to move to the native Markers Google maps api. This may happen soon. Thanks.

**Comment by stevenvandorpe** [comment] 2018-08-01 13:11
I have the same problem with the marker on a Windows machine. Checking the browser console I can see two different errors popping up:
`* Failed to load resource: net::ERR_FILE_NOT_FOUND
`* GET file:///C:/UsersStevenDesktoppythonGPXgmplotmarkers/6495ED.png 0 ()
I notice two things here:
1. The file location is missing slashes
2. Even if the slashes would be there, the file would still not be found, since this is my project folder and not the module's folder.
Thanks for letting me now if this is of any help.
Cheers, Steven.

**Comment by nick-merlino** [comment] 2018-09-22 23:03
If you want a quick fix for Windows, just edit ~/AppData/Local/Programs/Python/Python37/Lib/site-packages/gmplot/gmplot.py about half way down. This is just a path problem.

Before:
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers\%s.png')

After
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png') # Note the change from '\' to '/'
self.coloricon = self.coloricon.replace('\\', '\\\\')

**Comment by pinhao1994** [comment] 2018-09-28 00:40
I have the same problem for MAC OS 10.13.6. Can you please let know why?

**Comment by lrosal1** [comment] 2018-10-22 13:31
@nick-merlino  Are you saying that the after code should be? (See Below.)

self.coloricon = os.path.join(os.path.dirname(file), 'markers%s.png').self.coloricon.replace('\', '\\')

**Comment by lrosal1** [comment] 2018-10-22 13:34
> 
> 
> If you want a quick fix for Windows, just edit ~/AppData/Local/Programs/Python/Python37/Lib/site-packages/gmplot/gmplot.py about half way down. This is just a path problem.
> 
> Before:
> self.coloricon = os.path.join(os.path.dirname(**file**), 'markers/%s.png')
> 
> After
> self.coloricon = os.path.join(os.path.dirname(**file**), 'markers%s.png') # Note the change from ' / ' to ' \ ' (without spaces)
> self.coloricon = self.coloricon.replace('\', '\\') # Note there were two backslashes, now 4

@nick-merlino Are you saying that the after code should be? (See Below.)

`self.coloricon = os.path.join(os.path.dirname(file), 'markers%s.png').self.coloricon.replace('\', '\\')`

**Comment by WilliamSNorth** [comment] 2019-01-10 04:17
> may happen soo

Yeah its only a windows issue, the same code works fine of my ubuntu system, native maps makers would be awesome!!!

Thanks again for your excellent project

**Comment by david03g** [comment] 2019-09-22 19:50
> 
> 
> If you want a quick fix for Windows, just edit ~/AppData/Local/Programs/Python/Python37/Lib/site-packages/gmplot/gmplot.py about half way down. This is just a path problem.
> 
> Before:
> self.coloricon = os.path.join(os.path.dirname(**file**), 'markers/%s.png')
> 
> After
> self.coloricon = os.path.join(os.path.dirname(**file**), 'markers%s.png') # Note the change from ' / ' to ' \ ' (without spaces)
> self.coloricon = self.coloricon.replace('\', '\\') # Note there were two backslashes, now 4

I tried this and it did not work. It's impossible to do the backslash replace because of escapement issues.

**Comment by frslm** [comment] 2019-10-19 17:15
@rau @david03g This works for me:
```
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png')
self.coloricon = self.coloricon.replace('/', '\\').replace('\\', '\\\\')
```

The first `replace()` ensures that everything's a backslash, while the second ensures that all backslashes are escaped.

**Comment by 55thSwiss** [comment] 2019-10-25 12:43
Similarly to the markers, are legends going to be added for Windows machines? For instance I have multiple routes plotted with different colors, a simple box showing color and label would be wonderful

**Comment by rau** [comment] 2019-10-25 13:17
@frslm worked for me too. I had to manually edit it in in the library installation folder. thank you :)

**Comment by frslm** [comment] 2019-10-27 18:50
> Similarly to the markers, are legends going to be added for Windows machines? For instance I have multiple routes plotted with different colors, a simple box showing color and label would be wonderful

@55thSwiss, that'd be a nice addition - you could create a new issue to track that request. The Google Maps [documentation](https://developers.google.com/maps/documentation/javascript/adding-a-legend) details how we could get started with this.

**Comment by frslm** [comment] 2020-04-28 04:27
Duplicate of #18.

**Closed** 2020-05-03 02:26 UTC
Labels: bug, duplicate

**Comment by NichaT** [comment] 2020-06-05 15:38
> @rau @david03g This works for me:
> 
> ```
> self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png')
> self.coloricon = self.coloricon.replace('/', '\\').replace('\\', '\\\\')
> ```
> 
> The first `replace()` ensures that everything's a backslash, while the second ensures that all backslashes are escaped.

Thanks! Worked for me.

**Comment by frslm** [comment] 2020-06-05 23:00
Anytime @NichaT! Heads up though, this is now fixed in master, so if you're able to pull the latest code down, you won't need to use this workaround.
