### ISSUE TITLE
ImportError: cannot import name '_StringWriter'

### ISSUE THREAD

**Issue by enavarro01** [gmplot/gmplot#140] opened 2020-05-14 04:56 UTC
ImportError: cannot import name '_StringWriter'

**Comment by frslm** [comment] 2020-05-14 06:24
@enavarro01, could you post the traceback here? And are you using Python 2 or 3?

To get this to run in the meantime, you can temporarily comment out that `_StringWriter` import as well as the function it's used in (`GoogleMapPlotter.get()`).

**Comment by enavarro01** [comment] 2020-05-15 06:46
Thanks Faris.

**Comment by enavarro01** [comment] 2020-05-15 06:49
I am using pyhton 3

**Comment by frslm** [comment] 2020-05-18 06:45
@enavarro01, it works on my end (Python 3) as well as on this project's Python 3 test suite. Is there any other info you could provide to help us figure out what's wrong? If you pull down a fresh copy of this repo and try to run it, do you still get this issue?

**Comment by frslm** [comment] 2020-05-30 17:16
I'll be closing this for now since I wasn't able to reproduce this and couldn't find a code snippet or traceback that shows this issue.

If it happens again, feel free to post a code snippet or traceback and I can reopen this.

**Closed by frslm** 2020-05-30 17:16 UTC
Labels: bug

**Comment by enavarro01** [comment] 2020-05-30 19:19
Thank you
