### ISSUE TITLE
Marker title does not appear on hover

### ISSUE THREAD

**Issue by Abdur91** [gmplot/gmplot#165] opened 2020-06-23 12:16 UTC
Hi.i am facing this issue where marker title is not being appearing on hover on the map when map gets generated. Following is my code

 `df = pd.read_csv('file.csv')
gmap = gmplot.GoogleMapPlotter((df['lat'].min() + df['lat'].max()) / 2.0, 
    (df['lng'].min() + df['lng'].max()) / 2.0, 14,
    apikey='xxxxxxx')

for index, row in df.iterrows():
        gmap.marker(row['lat'], row['lng'], color='red', title=row['mnemonic'])`

Interestingly if my csv file contains row >=255,the title do gets appear on mouse hover.But on larger dataset the title does not appear.

thanks

**Comment by frslm** [comment] 2020-06-23 23:48
@Abdur91 if you look at the raw HTML, do those markers that don't display a title actually have their `title` field set to some string?

You should see something like this for every marker:
```js
new google.maps.Marker({
    title: ..., // <-- should have a string
    icon: ...,
    position: ...,
    map: map
});
```

(Note to self: Might be related to #117)

**Comment by Abdur91** [comment] 2020-06-24 11:30
thanks for your reply .yes my title value is a string value,but still title appears only for 256 rows.greater than 256 rows it does not.
As you have referred issue 117.i am quite sure its related to that

**Comment by Abdur91** [comment] 2020-06-24 11:31
i need a fix to this as early as possible
thanks

**Comment by frslm** [comment] 2020-06-24 22:39
I was never able to reproduce this on my end with sample data - if it's not sensitive info, could you attach the .csv file (or something similar with fake data) here? And attaching your output HTML file (**without your API key**) here would help too.

**Comment by frslm** [comment] 2020-07-27 06:00
As with #117, I'll be closing this for now since I still can't reproduce this.

If it happens again, feel free to post a code snippet or traceback and I can reopen this.

**Closed by frslm** 2020-07-27 06:00 UTC
Labels: support
