### ISSUE TITLE
gmplot.py write_point problem.

### ISSUE THREAD

**Issue by yogeveran** [gmplot/gmplot#62] opened 2018-03-01 11:37 UTC
```
        f.write('\t\tvar img = new google.maps.MarkerImage(\'%s\');\n' %
                (self.coloricon % color))

```
Causes an error when coloricon is a path containing backslashes.

Suggestion:

change init function:
from :
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png')
to:
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png').replace('\\', '/')

**Comment by frslm** [comment] 2020-04-28 04:27
Duplicate of #18.

**Closed** 2020-05-03 02:26 UTC
Labels: bug, duplicate
