### ISSUE TITLE
Error: 'google' is undefined.

### ISSUE THREAD

**Issue by yyykkkyyy** [gmplot/gmplot#87] opened 2018-08-31 01:52 UTC
Hi,
I use this wonderful package. 
I' d like to ask about an error that "google is undefined.". This occurred at line 9 which contained in the generated HTML by this package.
When I get this error, Google map is not presented on browser.

I don't have google map's api key. So, is this error occurred by missing api key ?

However, I can use this package without this error on chrome and firefox with developer mode.
This error occurs on IE and Microsoft Edge.

What can I do to solve this problem ?

Thanks.

**Comment by vgm64** [comment] 2018-08-31 04:05
Can you attach or link to an example html page? Is the error in the JS console, or rendered on the web browser?

**Comment by frslm** [comment] 2020-04-26 23:10
@yyykkkyyy I was able to view the map in IE, but only after allowing scripts to run (some popup came up asking to allow or block scripts). Could you try that and see if it helps?

**Comment by frslm** [comment] 2020-05-31 07:13
I'll be closing this for now since I wasn't able to reproduce this and couldn't find a code snippet or traceback that shows this issue.

If it happens again, feel free to post a code snippet or traceback and I can reopen this.

**Closed by frslm** 2020-05-31 07:13 UTC
Labels: question
